### ISSUE TITLE
version bump to 0.0.15 for gulpfile.js?

### ISSUE THREAD

**Issue by samumist** [cgkineo/adapt-buildkit-gulp#12]
After updating gulp file version to 0.0.15 the system still claims a new version 0.0.15 is available. It turns out that the following line in the gulpfile.js needs  a bump.

var version = "0.0.14"

and thanks for building such a great tool.

**Comment by oliverfoster** [comment]
Thanks. I completely forgot.

**Comment by oliverfoster** [comment]
you may want to try the newest version 

installer for buildkits > https://github.com/oliverfoster/adapt-buildkits
new buildkit (replacement for gulp) > https://github.com/oliverfoster/adapt-buildkit-rub

**Comment by samumist** [comment]
Many thanks. I'll definitely give it try.

**Comment by samumist** [comment]
I'm able to build courses with rub on all the frameworks, i.e. adapt learning v1.1.1 and test build 2.0 and Kineo's framework.

Here's my workflow:

### on Adapt learning framework
- clone the framework
- run `adapt install` to install components and extensions
- run `adapt-buildkit install rub` in the framework directory to install the native build tool
- run `./rub -s` to build a course and serve it

### on KINEO framework
- run `adapt-setup install` to install sample course, theme, menu, components and extensions.
- run `adapt-buildkit install rub` in the `dev` directory to install the native build tool
- run './rub -s' to build courses and serve it.

All in all, this is a great tool, clean and fast, **love** it!

I've noticed after the version 0.0.29, there's a warning "Version out of date at v0.0.31 downloading v0.0.33" during the install. After successfully installed rub, I run './rub -V' it still gives me a version no. of v0.0.31. 

Install rub in another project, the warning shows up again and download it from web again. Earlier version (0.0.29) seems cached locally and installed really fast.

not sure if there's a glitch.

And thanks again for all these great tools.

**Comment by oliverfoster** [comment]
cool! i'm glad you like it. 

it was only really getting to the finished stage today. hence the bucket load of changes. 

i'll look into the version problem tomorrow. 

if you want to open issues on the repository i'd welcome them. at least then i can work through them one by one.

thanks for the feedback, it's much appreciated :)

**Comment by samumist** [comment]
Thanks.
The version problem is gone after a restart of the computer this morning. It must be something wrong at my end. Sorry for the false alarm.

Yes. I'll report issues on the repo in the future.

Have a nice day!
